/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as InitialSetupRouteImport } from './routes/initial-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as InitialSetupCreateVenueRouteImport } from './routes/initial-setup/create-venue'
import { Route as InitialSetupCreateAdminRouteImport } from './routes/initial-setup/create-admin'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InitialSetupRoute = InitialSetupRouteImport.update({
  id: '/initial-setup',
  path: '/initial-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitialSetupCreateVenueRoute = InitialSetupCreateVenueRouteImport.update({
  id: '/create-venue',
  path: '/create-venue',
  getParentRoute: () => InitialSetupRoute,
} as any)
const InitialSetupCreateAdminRoute = InitialSetupCreateAdminRouteImport.update({
  id: '/create-admin',
  path: '/create-admin',
  getParentRoute: () => InitialSetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/initial-setup': typeof InitialSetupRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/initial-setup/create-admin': typeof InitialSetupCreateAdminRoute
  '/initial-setup/create-venue': typeof InitialSetupCreateVenueRoute
  '/error/': typeof ErrorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/initial-setup': typeof InitialSetupRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/initial-setup/create-admin': typeof InitialSetupCreateAdminRoute
  '/initial-setup/create-venue': typeof InitialSetupCreateVenueRoute
  '/error': typeof ErrorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/initial-setup': typeof InitialSetupRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/initial-setup/create-admin': typeof InitialSetupCreateAdminRoute
  '/initial-setup/create-venue': typeof InitialSetupCreateVenueRoute
  '/error/': typeof ErrorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/initial-setup'
    | '/sign-in'
    | '/initial-setup/create-admin'
    | '/initial-setup/create-venue'
    | '/error/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/initial-setup'
    | '/sign-in'
    | '/initial-setup/create-admin'
    | '/initial-setup/create-venue'
    | '/error'
  id:
    | '__root__'
    | '/'
    | '/initial-setup'
    | '/sign-in'
    | '/initial-setup/create-admin'
    | '/initial-setup/create-venue'
    | '/error/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InitialSetupRoute: typeof InitialSetupRouteWithChildren
  SignInRoute: typeof SignInRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initial-setup': {
      id: '/initial-setup'
      path: '/initial-setup'
      fullPath: '/initial-setup'
      preLoaderRoute: typeof InitialSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initial-setup/create-venue': {
      id: '/initial-setup/create-venue'
      path: '/create-venue'
      fullPath: '/initial-setup/create-venue'
      preLoaderRoute: typeof InitialSetupCreateVenueRouteImport
      parentRoute: typeof InitialSetupRoute
    }
    '/initial-setup/create-admin': {
      id: '/initial-setup/create-admin'
      path: '/create-admin'
      fullPath: '/initial-setup/create-admin'
      preLoaderRoute: typeof InitialSetupCreateAdminRouteImport
      parentRoute: typeof InitialSetupRoute
    }
  }
}

interface InitialSetupRouteChildren {
  InitialSetupCreateAdminRoute: typeof InitialSetupCreateAdminRoute
  InitialSetupCreateVenueRoute: typeof InitialSetupCreateVenueRoute
}

const InitialSetupRouteChildren: InitialSetupRouteChildren = {
  InitialSetupCreateAdminRoute: InitialSetupCreateAdminRoute,
  InitialSetupCreateVenueRoute: InitialSetupCreateVenueRoute,
}

const InitialSetupRouteWithChildren = InitialSetupRoute._addFileChildren(
  InitialSetupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InitialSetupRoute: InitialSetupRouteWithChildren,
  SignInRoute: SignInRoute,
  ErrorIndexRoute: ErrorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
