/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as CreateVenueRouteImport } from './routes/create/venue'
import { Route as CreateStaffRouteImport } from './routes/create/staff'
import { Route as CreateBannedPersonRouteImport } from './routes/create/bannedPerson'
import { Route as CreateBanRouteImport } from './routes/create/ban'
import { Route as CreateAlertRouteImport } from './routes/create/alert'
import { Route as CreateAdminRouteImport } from './routes/create/admin'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateVenueRoute = CreateVenueRouteImport.update({
  id: '/create/venue',
  path: '/create/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateStaffRoute = CreateStaffRouteImport.update({
  id: '/create/staff',
  path: '/create/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBannedPersonRoute = CreateBannedPersonRouteImport.update({
  id: '/create/bannedPerson',
  path: '/create/bannedPerson',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBanRoute = CreateBanRouteImport.update({
  id: '/create/ban',
  path: '/create/ban',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAlertRoute = CreateAlertRouteImport.update({
  id: '/create/alert',
  path: '/create/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAdminRoute = CreateAdminRouteImport.update({
  id: '/create/admin',
  path: '/create/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/create/admin': typeof CreateAdminRoute
  '/create/alert': typeof CreateAlertRoute
  '/create/ban': typeof CreateBanRoute
  '/create/bannedPerson': typeof CreateBannedPersonRoute
  '/create/staff': typeof CreateStaffRoute
  '/create/venue': typeof CreateVenueRoute
  '/error/': typeof ErrorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/create/admin': typeof CreateAdminRoute
  '/create/alert': typeof CreateAlertRoute
  '/create/ban': typeof CreateBanRoute
  '/create/bannedPerson': typeof CreateBannedPersonRoute
  '/create/staff': typeof CreateStaffRoute
  '/create/venue': typeof CreateVenueRoute
  '/error': typeof ErrorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/create/admin': typeof CreateAdminRoute
  '/create/alert': typeof CreateAlertRoute
  '/create/ban': typeof CreateBanRoute
  '/create/bannedPerson': typeof CreateBannedPersonRoute
  '/create/staff': typeof CreateStaffRoute
  '/create/venue': typeof CreateVenueRoute
  '/error/': typeof ErrorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/create/admin'
    | '/create/alert'
    | '/create/ban'
    | '/create/bannedPerson'
    | '/create/staff'
    | '/create/venue'
    | '/error/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/create/admin'
    | '/create/alert'
    | '/create/ban'
    | '/create/bannedPerson'
    | '/create/staff'
    | '/create/venue'
    | '/error'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/create/admin'
    | '/create/alert'
    | '/create/ban'
    | '/create/bannedPerson'
    | '/create/staff'
    | '/create/venue'
    | '/error/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  CreateAdminRoute: typeof CreateAdminRoute
  CreateAlertRoute: typeof CreateAlertRoute
  CreateBanRoute: typeof CreateBanRoute
  CreateBannedPersonRoute: typeof CreateBannedPersonRoute
  CreateStaffRoute: typeof CreateStaffRoute
  CreateVenueRoute: typeof CreateVenueRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/venue': {
      id: '/create/venue'
      path: '/create/venue'
      fullPath: '/create/venue'
      preLoaderRoute: typeof CreateVenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/staff': {
      id: '/create/staff'
      path: '/create/staff'
      fullPath: '/create/staff'
      preLoaderRoute: typeof CreateStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/bannedPerson': {
      id: '/create/bannedPerson'
      path: '/create/bannedPerson'
      fullPath: '/create/bannedPerson'
      preLoaderRoute: typeof CreateBannedPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/ban': {
      id: '/create/ban'
      path: '/create/ban'
      fullPath: '/create/ban'
      preLoaderRoute: typeof CreateBanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/alert': {
      id: '/create/alert'
      path: '/create/alert'
      fullPath: '/create/alert'
      preLoaderRoute: typeof CreateAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/admin': {
      id: '/create/admin'
      path: '/create/admin'
      fullPath: '/create/admin'
      preLoaderRoute: typeof CreateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  CreateAdminRoute: CreateAdminRoute,
  CreateAlertRoute: CreateAlertRoute,
  CreateBanRoute: CreateBanRoute,
  CreateBannedPersonRoute: CreateBannedPersonRoute,
  CreateStaffRoute: CreateStaffRoute,
  CreateVenueRoute: CreateVenueRoute,
  ErrorIndexRoute: ErrorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
