/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntialSetup_rootRouteImport } from './routes/intial-setup/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as IntialSetupCreateVenueRouteImport } from './routes/intial-setup/create-venue'
import { Route as IntialSetupCreateAdminRouteImport } from './routes/intial-setup/create-admin'

const IntialSetup_rootRoute = IntialSetup_rootRouteImport.update({
  id: '/intial-setup/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntialSetupCreateVenueRoute = IntialSetupCreateVenueRouteImport.update({
  id: '/intial-setup/create-venue',
  path: '/intial-setup/create-venue',
  getParentRoute: () => rootRouteImport,
} as any)
const IntialSetupCreateAdminRoute = IntialSetupCreateAdminRouteImport.update({
  id: '/intial-setup/create-admin',
  path: '/intial-setup/create-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intial-setup': typeof IntialSetup_rootRoute
  '/intial-setup/create-admin': typeof IntialSetupCreateAdminRoute
  '/intial-setup/create-venue': typeof IntialSetupCreateVenueRoute
  '/error/': typeof ErrorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intial-setup': typeof IntialSetup_rootRoute
  '/intial-setup/create-admin': typeof IntialSetupCreateAdminRoute
  '/intial-setup/create-venue': typeof IntialSetupCreateVenueRoute
  '/error': typeof ErrorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intial-setup/__root': typeof IntialSetup_rootRoute
  '/intial-setup/create-admin': typeof IntialSetupCreateAdminRoute
  '/intial-setup/create-venue': typeof IntialSetupCreateVenueRoute
  '/error/': typeof ErrorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intial-setup'
    | '/intial-setup/create-admin'
    | '/intial-setup/create-venue'
    | '/error/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intial-setup'
    | '/intial-setup/create-admin'
    | '/intial-setup/create-venue'
    | '/error'
  id:
    | '__root__'
    | '/'
    | '/intial-setup/__root'
    | '/intial-setup/create-admin'
    | '/intial-setup/create-venue'
    | '/error/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntialSetup_rootRoute: typeof IntialSetup_rootRoute
  IntialSetupCreateAdminRoute: typeof IntialSetupCreateAdminRoute
  IntialSetupCreateVenueRoute: typeof IntialSetupCreateVenueRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intial-setup/__root': {
      id: '/intial-setup/__root'
      path: '/intial-setup'
      fullPath: '/intial-setup'
      preLoaderRoute: typeof IntialSetup_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intial-setup/create-venue': {
      id: '/intial-setup/create-venue'
      path: '/intial-setup/create-venue'
      fullPath: '/intial-setup/create-venue'
      preLoaderRoute: typeof IntialSetupCreateVenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intial-setup/create-admin': {
      id: '/intial-setup/create-admin'
      path: '/intial-setup/create-admin'
      fullPath: '/intial-setup/create-admin'
      preLoaderRoute: typeof IntialSetupCreateAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntialSetup_rootRoute: IntialSetup_rootRoute,
  IntialSetupCreateAdminRoute: IntialSetupCreateAdminRoute,
  IntialSetupCreateVenueRoute: IntialSetupCreateVenueRoute,
  ErrorIndexRoute: ErrorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
